### ISSUE TITLE
Way to be notified of new events

### ISSUE THREAD

**Issue by catwell** [hackerevents/hackerevents#4] opened 2016-09-01 12:59 UTC
As a user, I want to be notified somehow when new events are added to the list.

What I am thinking about is something like:
- a way to subscribe by email; or
- a feed (RSS / Atom); or
- a Twitter bot.

I would personally prefer the second solution.

As a workaround I can subscribe to the feed for this repository, but then I am also notified on code changes which do not add new events.

**Comment by frankrousseau** [comment] 2016-09-01 13:03
Thank you @catwell for this enhancement proposal.

I prefer the second option too (at least it's easier to implement). Feel free to contribute to add the feed. The code is short and requires no dependency to work on.

_NB: As a workaround, you can check the commit contents of the gh-pages branch._

**Comment by catwell** [comment] 2016-09-04 17:58
To do this, I need a date of last update for an event, or at least a date of creation.

I can see two solutions for this:
- The simplest one is to add it to the event format, alongside start and end.
- It is also possible to take the date of the latest Git commit for the file. However this will add a git-related dependency to the script.

A third solution would be to use the last modification time of the file but my experience is that this is a bad idea, because it ties the build to a single machine.

What solution looks best to to? I would personally be in favor of the first one.

(Note: you can see WIP for this feature [here](https://github.com/catwell/hackerevents/)).

**Comment by frankrousseau** [comment] 2016-09-04 22:19
Yep the first one looks to be the simplest. But you have to handle the case where this date is not present.

**Comment by frankrousseau** [comment] 2016-09-11 22:03
Your addititon is now merged. But you sort events by start date, which makes the added date useless. Was that the intended behavior?

**Comment by catwell** [comment] 2016-09-12 06:45
No, that was an oversight. Fixed in #11.

**Comment by frankrousseau** [comment] 2016-09-12 15:49
This issue was fixed by your PR. I close it. Thx for reporting and for the implementation.

**Closed as completed** 2016-09-13 14:06 UTC
Labels: enhancement
